name: kite_util
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  kite_util_launcher: { path: ../kite_util_launcher }
  kite_util_logger: { path: ../kite_util_logger }
  kite_util_rule: { path: ../kite_util_rule }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
