name: kite_sit_library_session
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1             # Encryption (AES)
  crypto: ^3.0.1              # Hash (MD5)
  dio: ^4.0.4
  kite_session_common: { path: ../kite_session_common }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
