# The pubspec file
# https://dart.dev/tools/pub/pubspec

name: kite
version: 1.4.4+31

description: '上应小风筝 APP，基于 Flutter。'

homepage:      https://github.com/SIT-kite/kite-app
repository:    https://github.com/SIT-kite/kite-app
issue_tracker: https://github.com/SIT-kite/kite-app/issues
documentation: https://github.com/SIT-kite/kite-app#readme

publish_to: none
environment: { sdk: '>=2.17.0 <3.0.0', flutter: ^3.0.0 }

# ------------------------------------------------------------------------------

# View pub packages at: https://pub.dev/packages/{{package_name}}
#               mirror: https://pub.flutter-io.cn/packages/{{package_name}}

dependencies:

  flutter: { sdk: flutter }

  device_info_plus_platform_interface: ^2.6.1

  # Basic
  intl: ^0.17.0               # i18n & l10n
  logger: ^1.1.0              # logger
  catcher: ^0.6.9             # Error handling
  path_provider: ^2.0.8       # Path

  # String and charset
  format: ^1.1.1              # String formatting
  enough_convert: ^1.6.0      # Character encoding

  # Cryptography
  encrypt: ^5.0.1             # Encryption (AES)
  crypto: ^3.0.1              # Hash (MD5)
  uuid: ^3.0.5                # UUID generator

  # File format
  ical: ^0.2.2                # iCalendar file generator
  json_serializable: ^6.3.1   # JSON
  json_annotation: ^4.6.0     # JSON code generation
  beautiful_soup_dart: ^0.3.0 # HTML parser

  # hive (key-value database)
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  # Dio (http client)
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0

  # Webview and browser related
  webview_flutter: ^3.0.0
  fk_user_agent: ^2.0.1
  flutter_widget_from_html: ^0.8.5

  # Email
  enough_mail: ^2.1.0
  enough_mail_html: ^2.0.0

  # Settings
  app_settings: ^4.1.1
  flutter_settings_screens: ^0.3.3-null-safety+2

  # Platform
  permission_handler: 10.0.0        # Android / iOS / Windows Permission
  quick_actions: ^0.6.0+9           # Android / iOS Home screen quick actions
  device_display_brightness: ^0.0.6 # Android / iOS screen brightness

  # Open with other APP/programs
  open_file: ^3.2.1                 # Open files
  url_launcher: ^6.0.17             # Open URLs
  image_picker: ^0.8.4+7            # Open Android / iOS system image picker
  file_picker: ^4.6.1               # Open system file picker

  # UI
  flash: ^2.0.3+1
  fl_chart: ^0.55.0
  text_scroll: ^0.1.0
  grouped_list: ^5.1.1
  pull_to_refresh: ^2.0.0
  dynamic_color_theme: ^2.0.0
  geopattern_flutter: { git: { url: https://github.com/SIT-kite/geopattern } }
  flutter_svg: ^1.1.0
  flutter_screenutil: ^5.5.2              # Screen adaptation
  flutter_native_splash: ^2.1.1           # Splash screen
  flutter_platform_widgets: ^2.0.0       # Platform aware widgets
  flutter_weather_bg_null_safety: ^1.0.0  # Weather background
  qr_flutter: ^4.0.0                      # Qr code generate
  mobile_scanner: ^2.0.0                  # qrcode scanner
  audioplayers: ^1.0.1                   # audio player
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  photo_view: ^0.14.0

  # Utils
  version: ^3.0.2               # Version comparison
  nfc_manager: ^3.1.0           # NFC
  flutter_phoenix: ^1.0.0       # Restart app
  package_info_plus: ^1.3.0     # Get package info (version)
  universal_platform: ^1.0.0+1  # dart.io.Platform API for Web
  check_vpn_connection: ^0.0.2  # Check VPN connection status
  synchronized: ^3.0.0+2        # lock
  stack_trace: ^1.10.0          # parse stacktrace

  # Desktop support
  window_manager: ^0.2.0

  kite_request_interface: { path: modules/kite_request_interface }
  kite_request_dio_adapter: { path: modules/kite_request_dio_adapter }
  kite_util: { path: modules/kite_util }


dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

# ------------------------------------------------------------------------------

flutter:

  uses-material-design: true

  fonts:
    # Iconfont for ywb.sit.edu.cn
    # For office module. So I named it office_iconfont.
    - family: office_iconfont
      fonts: [{ asset: assets/fonts/office_iconfont.ttf }]

    # Good night module
    - family: calligraphy
      fonts: [{ asset: assets/fonts/calligraphy.ttf }]

  assets:
    - assets/
    - assets/common/
    - assets/home/
    - assets/welcome/
    - assets/connectivity/
    - assets/campus_card/
    - assets/report/
    - assets/fonts/
    - assets/weather/
    - assets/wiki/
    - assets/score/
    - assets/library/
    - assets/timetable/
    - assets/course/
    - assets/night/
    - assets/game/
    - assets/game/tetris/
    - assets/mail/
    - assets/scanner/
    - assets/freshman/
    # Prompt sound.
    - assets/game/step.mp3
    - assets/scanner/beep.mp3

# See: https://pub.flutter-io.cn/packages/flutter_native_splash
flutter_native_splash:
  fullscreen: true
  color: '#FFFFFF'
  image: assets/icon.png
  # background_image: 'assets/background.png'
