name: kite_kite_session

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  kite_user_entity: { path: ../../../kite_user_entity }
  kite_session_common: { path: ../kite_session_common }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
