name: kite_sit_sso_session
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  synchronized: ^3.0.0+2        # lock
  encrypt: ^5.0.1             # Encryption (AES)
  beautiful_soup_dart: ^0.3.0 # HTML parser
  dio: ^4.0.4
  kite_util: { path: ../kite_util }
  kite_ocr: { path: ../kite_ocr }
  kite_request_interface: { path: ../kite_request_interface }
  kite_request_dio_adapter: { path: ../kite_request_dio_adapter }
  kite_exception: { path: ../kite_exception }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
