name: kite_component

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kite_future_builder: { path: modules/kite_future_builder }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
