name: kite_session

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kite_sit_report_session: { path: modules/kite_sit_report_session }
  kite_sit_office_session: { path: modules/kite_sit_office_session }
  kite_sit_library_session: { path: modules/kite_sit_library_session }
  kite_sit_app_session: { path: modules/kite_sit_app_session }
  kite_sit_edu_session: { path: modules/kite_sit_edu_session }
  kite_sit_sso_session: { path: modules/kite_sit_sso_session }
  kite_kite_session: { path: modules/kite_kite_session }
  kite_sit_sc_session: { path: modules/kite_sit_sc_session }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
