name: kite_feature_route
description: A new Flutter package project.
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kite_feature_base: { path: ../kite_feature_base }


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
