name: kite_weather_entity

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.3.1   # JSON
  json_annotation: ^4.6.0     # JSON code generation
  hive: ^2.0.5
  kite_hive_type_id_pool: { path: ../../../../../kite_hive_type_id_pool }

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
