name: kite_feature_weather

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kite_weather_entity: { path: modules/kite_weather_entity }
  kite_weather_service_interface: { path: modules/kite_weather_service_interface }
  kite_weather_service_impl: { path: modules/kite_weather_service_impl }


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
