name: kite_platform_widget


environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^1.0.0+1  # dart.io.Platform API for Web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
