name: kite_sit_edu_session


environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kite_request_interface: { path: ../kite_request_interface }
  kite_util: { path: ../kite_util }
  kite_sit_sso_session: { path: ../kite_sit_sso_session }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
