name: kite_sit_office_session


environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1              # Hash (MD5)
  dio: ^4.0.4
  kite_util: { path: ../kite_util }
  kite_request_interface: { path: ../kite_request_interface }
  kite_request_dio_adapter: { path: ../kite_request_dio_adapter }
  kite_exception: { path: ../kite_exception }
  kite_storage_auth_interface: { path: ../kite_storage_interface/modules/kite_storage_auth_interface }
  kite_storage_jwt_interface: { path: ../kite_storage_interface/modules/kite_storage_jwt_interface }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
