name: Bump Build Numer

on:
  push: { tags: [ '*' ] }
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
          cache: true

      - name: Bump Flutter Build Number
        run: |
          flutter pub get
          flutter pub global activate cider
          flutter pub global run cider bump build

      - name: Get Flutter Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Update Xcode Build Number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.get_flutter_version.outputs.version_number }}
          build-number: ${{ steps.get_flutter_version.outputs.build_number }}
          project-path: ios

      - name: Get Flutter Version
        id: lastest_flutter_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Push Build Number Update
        run: |
          git add .
          git commit -m "Update: Bump Build Number to ${{ steps.lastest_flutter_version.outputs.build_number }}"
          git push origin master

  notify:
    runs-on: ubuntu-latest
    needs: bump
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Lastest Flutter Version
        id: lastest_flutter_version
        uses: its404/get-flutter-version@v1.0.0

      - name: 🤖 Telegram Notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🏷️ [KiteApp](https://github.com/SIT-kite/kite-app) Build Number Update to *${{ steps.lastest_flutter_version.outputs.build_number }}*
