name: KiteApp

on:
  push:
  pull_request: { branches: [ master ] }

jobs:

  # flutter pub get + flutter analyze
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.1
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }} # use ${{ hashFiles('pubspec.lock') }} when available
          restore-keys: |
            pub-${{ github.ref }}-
            pub-

      - name: 📌 Flutter Code Generate
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter pub run flutter_native_splash:create

      - name: 📌 Cache pub
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Cache Workspace
        uses: actions/cache@v2
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}


  # flutter build apk, cache build/
  build-Android:
    needs: lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.1
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Restore Workspace
        uses: actions/cache@v2
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}

      - name: 🏗️ Build Apk (arm64,android-x64)
        run: flutter build apk --split-per-abi --target-platform android-arm64,android-x64

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.APK_SIGN_JKS_BASE64 }}
          alias: ${{ secrets.APK_SIGN_ALIAS }}
          keyStorePassword: ${{ secrets.APK_SIGN_PASS }}

      - name: 📌 Cache Build
        uses: actions/cache@v2
        with:
          path: build/
          key: apk-${{ github.ref }}-${{ github.sha }}

    # flutter build ios
  build-iOS:
    runs-on: macos-latest
    needs: lint
    steps:

      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: latest-stable }

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.1
          channel: stable
          cache: true

      - name: 📌 Restore pub cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache/
            .dart_tool/
            .packages
            .flutter-plugins
            .flutter-plugins-dependencies
            pubspec.lock
          key: pub-${{ github.ref }}-${{ github.sha }}

      - name: 📌 Restore Workspace
        uses: actions/cache@v2
        with:
          path: |
            lib/
          key: app-${{ github.ref }}-${{ github.sha }}

      - name: 🏗️ Build iOS
        run: flutter build ios --no-codesign

  build-Windows:
    runs-on: windows-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.1
          channel: stable
          cache: true

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build windows

  # 临时关闭Linux平台的Action
  #  build-Linux:
  #    runs-on: ubuntu-latest
  #    needs: lint
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: subosito/flutter-action@v2
  #        with: { channel: stable, cache: true }
  #      - run: |
  #          sudo apt-get update -y
  #          sudo apt-get install -y ninja-build libgtk-3-dev
  #      - run: flutter pub get
  #      - run: flutter pub run build_runner build --delete-conflicting-outputs
  #      - run: flutter build linux

  # Upload apk
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build-Android
    steps:

      - uses: nelonoel/branch-name@v1.0.1

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - name: 📌 Get apk from cache
        uses: actions/cache@v2
        with:
          path: build/
          key: apk-${{ github.ref }}-${{ github.sha }}

      - name: ✏️ Rename apk file
        run: |
          cd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release-signed.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          mv app-x86_64-release-signed.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk

      - name: 🤖 Upload apk by bot
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          message: "🚀 Android arm64-v8a Apk Build by Github Actions"

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SECRET }}
          source: ./build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk
          target: /var/kite/web/apk/
          strip_components: 5

      - name: SSH Remote Rename apk
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SECRET }}
          script: |
            rm /var/kite/web/apk/sit-kite-arm64-v8a-release-latest.apk
            mv /var/kite/web/apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release-signed.apk /var/kite/web/apk/sit-kite-arm64-v8a-release-latest.apk

      - name: 🤖 Upload apk by bot
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-x86_64-release-signed.apk
          message: "🚀 Android x86_64 Apk Build by Github Actions"

  # Send notification
  notification:
    runs-on: ubuntu-latest
    needs: [ upload ]
    if: github.event_name != 'pull_request' && always()
    steps:

      - uses: technote-space/workflow-conclusion-action@v2
      - uses: nelonoel/branch-name@v1.0.1
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with: { length: 7 }

      - name: 🤖 Build Success Notification
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🎉 [KiteApp](https://github.com/SIT-kite/kite-app)  Build  *${{ env.WORKFLOW_CONCLUSION }}*

            Author: *${{ github.actor }}*

            Message: *${{ github.event.head_commit.message }}*

            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})

            Branch: *${{ env.BRANCH_NAME }}*

      - name: 🤖 Build Fail Notification
        if: env.WORKFLOW_CONCLUSION != 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🔴 [KiteApp](https://github.com/SIT-kite/kite-app)  Build  *${{ env.WORKFLOW_CONCLUSION }}*

            Author: *${{ github.actor }}*

            Message: *${{ github.event.head_commit.message }}*

            Commit: [${{ env.SHA }}](https://github.com/${{ github.repository }}/commit/${{ env.SHA }})

            Branch: *${{ env.BRANCH_NAME }}*

      - name: 🤖 PR Merged Notification
        if: github.event.pull_request.merged == true && env.WORKFLOW_CONCLUSION == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            🎉 [KiteApp](https://github.com/SIT-kite/kite-app)  PR [#${{github.event.number}}](https://github.com/SIT-kite/kite-app/pull/${{github.event.number}}) Merged!

            Author: *${{ github.actor }}*

            Message: *${{ github.event.pull_request.title }}*

            Branch: *${{ env.BRANCH_NAME }}*
